---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: kind-1.12
    groups:
      - k8s
    image: bsycorp/kind:latest-1.12
    privileged: True
    override_command: no
    exposed_ports:
      - 8443/tcp
      - 10080/tcp
    published_ports:
      - 0.0.0.0:${TEST_CLUSTER_PORT:-8443}:8443/tcp
    pre_build_image: yes
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: True
  env:
    K8S_AUTH_KUBECONFIG: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
    KUBECONFIG: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
    KIND_PORT: '${TEST_CLUSTER_PORT:-8443}'
    OBJC_DISABLE_INITIALIZE_FORK_SAFETY: 'YES'
verifier:
  name: ansible
